"""update votes_score in comments

Revision ID: 193dab21effc
Revises: 6d06345f21f4
Create Date: 2026-04-21 19:30:02.066295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '193dab21effc'
down_revision: Union[str, Sequence[str], None] = '6d06345f21f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('votes_score', sa.Integer(), nullable=False))
    op.drop_column('comments', 'vote_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('vote_score', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('comments', 'votes_score')
    # ### end Alembic commands ###
