"""init

Revision ID: 6d1c13b51636
Revises: 
Create Date: 2026-04-20 20:02:44.470820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6d1c13b51636'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_communities_name'), 'communities', ['name'], unique=True)
    op.alter_column('community_members', 'role',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.Enum('member', 'moderator', 'admin', name='role'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('community_members', 'role',
               existing_type=sa.Enum('member', 'moderator', 'admin', name='role'),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_index(op.f('ix_communities_name'), table_name='communities')
    # ### end Alembic commands ###
